/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Hassan Khany
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    Connection con=null;
    CardLayout cat;
   
    
    public MainPage() throws SQLException {
        initComponents();
        cat=(CardLayout)(cats.getLayout());
        con=NewMain.connect();
        retrieveElectronics();
        retrieveBeauty();
        retrieveSports();
        retrieveHealth();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clients = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        healthButton = new javax.swing.JButton();
        clothsButton = new javax.swing.JButton();
        electronicsButton = new javax.swing.JButton();
        sportsButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cats = new javax.swing.JPanel();
        sports = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sportsTable = new javax.swing.JTable();
        beauty = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        beautyTable = new javax.swing.JTable();
        health = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        healthTable = new javax.swing.JTable();
        electronics = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        electronicsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        show = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 134, 179));

        healthButton.setText("Health");
        healthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthButtonActionPerformed(evt);
            }
        });

        clothsButton.setText("Fashion & Beauty");
        clothsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothsButtonActionPerformed(evt);
            }
        });

        electronicsButton.setText("Electronics");
        electronicsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronicsButtonActionPerformed(evt);
            }
        });

        sportsButton.setText("Sports");
        sportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hassan Khany\\Downloads\\123.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(electronicsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sportsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clothsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(healthButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(electronicsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sportsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clothsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(healthButton)
                .addGap(179, 179, 179))
        );

        cats.setLayout(new java.awt.CardLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sports");

        sportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        jScrollPane2.setViewportView(sportsTable);
        if (sportsTable.getColumnModel().getColumnCount() > 0) {
            sportsTable.getColumnModel().getColumn(0).setResizable(false);
            sportsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout sportsLayout = new javax.swing.GroupLayout(sports);
        sports.setLayout(sportsLayout);
        sportsLayout.setHorizontalGroup(
            sportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        sportsLayout.setVerticalGroup(
            sportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cats.add(sports, "card2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fashion & Beauty");

        beautyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        jScrollPane3.setViewportView(beautyTable);
        if (beautyTable.getColumnModel().getColumnCount() > 0) {
            beautyTable.getColumnModel().getColumn(0).setResizable(false);
            beautyTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout beautyLayout = new javax.swing.GroupLayout(beauty);
        beauty.setLayout(beautyLayout);
        beautyLayout.setHorizontalGroup(
            beautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(beautyLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        beautyLayout.setVerticalGroup(
            beautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beautyLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cats.add(beauty, "card2");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Health");

        healthTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        jScrollPane4.setViewportView(healthTable);
        if (healthTable.getColumnModel().getColumnCount() > 0) {
            healthTable.getColumnModel().getColumn(0).setResizable(false);
            healthTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout healthLayout = new javax.swing.GroupLayout(health);
        health.setLayout(healthLayout);
        healthLayout.setHorizontalGroup(
            healthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(healthLayout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        healthLayout.setVerticalGroup(
            healthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cats.add(health, "card2");

        electronicsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        jScrollPane1.setViewportView(electronicsTable);
        if (electronicsTable.getColumnModel().getColumnCount() > 0) {
            electronicsTable.getColumnModel().getColumn(0).setResizable(false);
            electronicsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Electronics");

        javax.swing.GroupLayout electronicsLayout = new javax.swing.GroupLayout(electronics);
        electronics.setLayout(electronicsLayout);
        electronicsLayout.setHorizontalGroup(
            electronicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(electronicsLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        electronicsLayout.setVerticalGroup(
            electronicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(electronicsLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        cats.add(electronics, "card2");

        jButton1.setBackground(new java.awt.Color(0, 115, 153));
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("SignIn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientsLayout = new javax.swing.GroupLayout(clients);
        clients.setLayout(clientsLayout);
        clientsLayout.setHorizontalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientsLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clientsLayout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(cats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        clientsLayout.setVerticalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(422, 422, 422))
            .addGroup(clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientsLayout.createSequentialGroup()
                    .addContainerGap(43, Short.MAX_VALUE)
                    .addComponent(cats, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clients, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SignIn signin;
        try {
            signin = new SignIn();
            signin.setVisible(true);
        dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void sportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsButtonActionPerformed
        cats.removeAll();
        cats.add(sports);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsButtonActionPerformed

    private void electronicsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronicsButtonActionPerformed
        cats.removeAll();
        cats.add(electronics);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_electronicsButtonActionPerformed

    private void clothsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothsButtonActionPerformed
        cats.removeAll();
        cats.add(beauty);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_clothsButtonActionPerformed

    private void healthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthButtonActionPerformed
        cats.removeAll();
        cats.add(health);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_healthButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainPage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beauty;
    private javax.swing.JTable beautyTable;
    private javax.swing.JPanel cats;
    private javax.swing.JPanel clients;
    private javax.swing.JButton clothsButton;
    private javax.swing.JPanel electronics;
    private javax.swing.JButton electronicsButton;
    private javax.swing.JTable electronicsTable;
    private javax.swing.JPanel health;
    private javax.swing.JButton healthButton;
    private javax.swing.JTable healthTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel show;
    private javax.swing.JPanel sports;
    private javax.swing.JButton sportsButton;
    private javax.swing.JTable sportsTable;
    // End of variables declaration//GEN-END:variables

    public void retrieveElectronics() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) electronicsTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0;
        PreparedStatement pst;
        String get="SELECT Name,Price,stock,Detail  FROM `product` WHERE Category='electronics'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
              Object data[]={name,price,stock,detail};
            eTable.addRow(data);
            
        }   
    }
     public void retrieveSports() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) sportsTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0;
        PreparedStatement pst;
        String get="SELECT Name,Price,stock,Detail  FROM `product` WHERE Category='sports'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
          
            Object data[]={name,price,stock,detail};
            eTable.addRow(data);
            
        }   
    }
     public void retrieveBeauty() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) beautyTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0;
        PreparedStatement pst;
        String get="SELECT Name,Price,stock,Detail  FROM `product` WHERE Category='beauty'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
            
            Object data[]={name,price,stock,detail};
            eTable.addRow(data); 
        }   
    }
     public void retrieveHealth() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) healthTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0;
        PreparedStatement pst;
        String get="SELECT Name,Price,stock,Detail  FROM `product` WHERE Category='health'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
            
            Object data[]={name,price,stock,detail};
            eTable.addRow(data);
            
        }   
    }

}
