/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;
/**
 *
 * @author Hassan Khany
 */
public class RegisteredClients extends javax.swing.JFrame {

    /**
     * Creates new form RegisteredClients
     */
    Connection con=null;
    CardLayout cat;
    String uName;
    
    String cartName, cartDetail;
    int cartPrice=0,cartStock=0,cartProductId=0,cartTotal=0;
    
    
    public RegisteredClients() throws SQLException {
        
        
        
    }
    
    public RegisteredClients(String name) throws SQLException
    {
        initComponents();
        cat=(CardLayout)(cats.getLayout());
        con=NewMain.connect();
        retrieveElectronics();
        retrieveBeauty();
        retrieveSports();
        retrieveHealth();
        uName=name;
         setUsername.setText(uName);
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        registeredClients = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        healthButton1 = new javax.swing.JButton();
        clothsButton1 = new javax.swing.JButton();
        electronicsButton1 = new javax.swing.JButton();
        sportsButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cats = new javax.swing.JPanel();
        electronics = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        electronicsTable = new javax.swing.JTable();
        sports = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sss = new javax.swing.JScrollPane();
        sportsTable = new javax.swing.JTable();
        beauty = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        aaa = new javax.swing.JScrollPane();
        beautyTable = new javax.swing.JTable();
        health = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        hhh = new javax.swing.JScrollPane();
        healthTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getQ = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setUsername = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cart = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        back = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        showTotal = new javax.swing.JLabel();
        removeProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(0, 134, 179));

        healthButton1.setText("Health");
        healthButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthButton1ActionPerformed(evt);
            }
        });

        clothsButton1.setText("Fashion & Beauty");
        clothsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothsButton1ActionPerformed(evt);
            }
        });

        electronicsButton1.setText("Electronics");
        electronicsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronicsButton1ActionPerformed(evt);
            }
        });

        sportsButton1.setText("Sports");
        sportsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Online Shopping");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Store");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(electronicsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sportsButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clothsButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(healthButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(77, 77, 77)
                .addComponent(electronicsButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sportsButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clothsButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(healthButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cats.setLayout(new java.awt.CardLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Electronics");

        electronicsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        electronicsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electronicsTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(electronicsTable);

        javax.swing.GroupLayout electronicsLayout = new javax.swing.GroupLayout(electronics);
        electronics.setLayout(electronicsLayout);
        electronicsLayout.setHorizontalGroup(
            electronicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(electronicsLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, electronicsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        electronicsLayout.setVerticalGroup(
            electronicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(electronicsLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cats.add(electronics, "card2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sports");

        sportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        sportsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sportsTableMouseClicked(evt);
            }
        });
        sss.setViewportView(sportsTable);

        javax.swing.GroupLayout sportsLayout = new javax.swing.GroupLayout(sports);
        sports.setLayout(sportsLayout);
        sportsLayout.setHorizontalGroup(
            sportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sss, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        sportsLayout.setVerticalGroup(
            sportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sportsLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cats.add(sports, "card2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fashion & Beauty");

        beautyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        beautyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beautyTableMouseClicked(evt);
            }
        });
        aaa.setViewportView(beautyTable);

        javax.swing.GroupLayout beautyLayout = new javax.swing.GroupLayout(beauty);
        beauty.setLayout(beautyLayout);
        beautyLayout.setHorizontalGroup(
            beautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aaa, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addGroup(beautyLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        beautyLayout.setVerticalGroup(
            beautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beautyLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cats.add(beauty, "card2");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Health");

        healthTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Stock/Items", "Product Detail"
            }
        ));
        healthTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthTableMouseClicked(evt);
            }
        });
        hhh.setViewportView(healthTable);

        javax.swing.GroupLayout healthLayout = new javax.swing.GroupLayout(health);
        health.setLayout(healthLayout);
        healthLayout.setHorizontalGroup(
            healthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(hhh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        healthLayout.setVerticalGroup(
            healthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hhh, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        cats.add(health, "card2");

        jLabel1.setText("Quantity");

        getQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getQActionPerformed(evt);
            }
        });

        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getQ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getQ)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        cartButton.setBackground(new java.awt.Color(0, 115, 153));
        cartButton.setForeground(new java.awt.Color(240, 240, 240));
        cartButton.setText("Cart");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 115, 153));
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout registeredClientsLayout = new javax.swing.GroupLayout(registeredClients);
        registeredClients.setLayout(registeredClientsLayout);
        registeredClientsLayout.setHorizontalGroup(
            registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registeredClientsLayout.createSequentialGroup()
                .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registeredClientsLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registeredClientsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registeredClientsLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(setUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(registeredClientsLayout.createSequentialGroup()
                        .addGap(644, 644, 644)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registeredClientsLayout.createSequentialGroup()
                    .addContainerGap(256, Short.MAX_VALUE)
                    .addComponent(cats, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        registeredClientsLayout.setVerticalGroup(
            registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registeredClientsLayout.createSequentialGroup()
                .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(registeredClientsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(setUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addGap(350, 350, 350)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(registeredClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registeredClientsLayout.createSequentialGroup()
                    .addContainerGap(39, Short.MAX_VALUE)
                    .addComponent(cats, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(171, 171, 171)))
        );

        panel.add(registeredClients, "card2");

        jPanel2.setBackground(new java.awt.Color(0, 134, 179));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hassan Khany\\Downloads\\favorite-cart.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hassan Khany\\Downloads\\123.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S_no", "Product Name", "Price", "Quantity", "Total"
            }
        ));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cartTable);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        checkout.setText("Checkout");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Bill:");

        removeProduct.setText("Remove Product");
        removeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cartLayout = new javax.swing.GroupLayout(cart);
        cart.setLayout(cartLayout);
        cartLayout.setHorizontalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(cartLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(cartLayout.createSequentialGroup()
                                .addGroup(cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(removeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        cartLayout.setVerticalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(29, 29, 29))
        );

        panel.add(cart, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void healthButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthButton1ActionPerformed
    cats.removeAll();
        cats.add(health);
        cats.repaint();
        cats.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_healthButton1ActionPerformed

    private void clothsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothsButton1ActionPerformed
       cats.removeAll();
        cats.add(beauty);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_clothsButton1ActionPerformed

    private void electronicsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronicsButton1ActionPerformed
         cats.removeAll();
        cats.add(electronics);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_electronicsButton1ActionPerformed

    private void sportsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsButton1ActionPerformed
       cats.removeAll();
        cats.add(sports);
        cats.repaint();
        cats.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainPage main;
        try {
            main = new MainPage();
            main.setVisible(true);
        dispose();
        } catch (SQLException ex) {
            Logger.getLogger(RegisteredClients.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
       cartTotal=0;
        panel.removeAll();
            panel.add(cart);
            panel.repaint();
            panel.revalidate();
        try {
            DefaultTableModel eTable = (DefaultTableModel) cartTable.getModel();
            eTable.setRowCount(0);
            String name,detail,category;
            int id,price=0,stock=0;
            com.mysql.jdbc.PreparedStatement pst;
            String get="SELECT S_no,Name,Price,Items  FROM `cart` where UserName=?";
           
            pst =(com.mysql.jdbc.PreparedStatement) con.prepareStatement(get);
           pst.setString(1,uName);
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("S_no");
                name =rs.getString("Name");
                price =rs.getInt("Price");
                stock =rs.getInt("Items");
                
                //JOptionPane.showMessageDialog(null,name);
                cartTotal=cartTotal+(price*stock);
                Object data[]={id,name,price,stock,price*stock};
                eTable.addRow(data);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(RegisteredClients.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        showTotal.setText(String.valueOf(cartTotal));
       
    }//GEN-LAST:event_cartButtonActionPerformed

    private void getQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getQActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int id1=0;
    
            try {
                
                com.mysql.jdbc.PreparedStatement pst;
                String get="SELECT S_no  FROM `cart`";
                pst =(com.mysql.jdbc.PreparedStatement) con.prepareStatement(get);
                ResultSet rs=pst.executeQuery();
                
                while(rs.next())
                {
                    id1 =rs.getInt("S_no");
                
                }
                id1++;
                // JOptionPane.showMessageDialog(null,id);
            }
            catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
              
         //  JOptionPane.showMessageDialog(null,id1);
             int q=0;
            try 
                {                                         
                   
                    q=(Integer.parseInt(getQ.getText()));
                    if(q>cartStock)
                    {
                        JOptionPane.showMessageDialog(null,"Entered Quantity is Greater than Stock Available");
                    }
                    else
                    {
                        String get1="INSERT INTO `cart` (`S_no`, `UserName`, `Name`, `Price`,`Items`,`Total`) VALUES (?, ?, ?, ?, ?, ?)";
                        java.sql.PreparedStatement pst1;
                        pst1 = con.prepareStatement(get1);
                        pst1.setInt(1,id1);
                        pst1.setString(2, uName);
                        pst1.setString(3, cartName);
                        pst1.setInt(4, cartPrice);
                        pst1.setInt(5, (Integer.parseInt(getQ.getText())));
                        pst1.setInt(6,cartPrice*q);

                         if(pst1.executeUpdate()>0)
                           {
                               JOptionPane.showMessageDialog(null,"Product Added! to Cart");
                           }
                    }

               } 
                catch (SQLException ex)
                {
                    Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
            
            
             try 
                {                                         

                    String get1="UPDATE `product` SET `Stock` = ? WHERE `product`.`ProductID` ="+selectedItem;
                    java.sql.PreparedStatement pst1;
                    pst1 = con.prepareStatement(get1);
                    pst1.setInt(1,cartStock-q);
                    
                    

                     if(pst1.executeUpdate()>0)
                       {
                          // JOptionPane.showMessageDialog(null,"Product Updated!");
                       }

               } 
                catch (SQLException ex)
                {
                    Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                }
             
        try {
            retrieveElectronics();
            retrieveHealth();
            retrieveBeauty();
            retrieveSports();
//JOptionPane.showMessageDialog(null,q);
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(RegisteredClients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void electronicsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electronicsTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) electronicsTable.getModel();
        int i=electronicsTable.getSelectedRow();
        cartProductId=(int) model.getValueAt(i,0);
        cartName=model.getValueAt(i,1).toString();
        
        cartPrice=(int) model.getValueAt(i,2);
        
        cartStock=(int) model.getValueAt(i,3);
        
        cartDetail=model.getValueAt(i,4).toString();
        //JOptionPane.showMessageDialog(null,cartName);

        
        selectedItem=(int)model.getValueAt(i,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_electronicsTableMouseClicked

    private void sportsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sportsTableMouseClicked
         DefaultTableModel model = (DefaultTableModel) sportsTable.getModel();
        int i=sportsTable.getSelectedRow();
        
        cartProductId=(int) model.getValueAt(i,0);
        cartName=model.getValueAt(i,1).toString();
        
        cartPrice=(int) model.getValueAt(i,2);
        
        cartStock=(int) model.getValueAt(i,3);
        
        cartDetail=model.getValueAt(i,4).toString();
        //JOptionPane.showMessageDialog(null,cartName);

        
        selectedItem=(int)model.getValueAt(i,0);

        // TODO add your handling code here:
    }//GEN-LAST:event_sportsTableMouseClicked

    private void beautyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beautyTableMouseClicked
         DefaultTableModel model = (DefaultTableModel) beautyTable.getModel();
        int i=beautyTable.getSelectedRow();
        
        cartProductId=(int) model.getValueAt(i,0);
        cartName=model.getValueAt(i,1).toString();
        
        cartPrice=(int) model.getValueAt(i,2);
        
        cartStock=(int) model.getValueAt(i,3);
        
        cartDetail=model.getValueAt(i,4).toString();
        //JOptionPane.showMessageDialog(null,cartName);

        selectedItem=(int)model.getValueAt(i,0);


        // TODO add your handling code here:
    }//GEN-LAST:event_beautyTableMouseClicked

    private void healthTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthTableMouseClicked
         DefaultTableModel model = (DefaultTableModel) healthTable.getModel();
        int i=healthTable.getSelectedRow();
        
        cartProductId=(int) model.getValueAt(i,0);
        cartName=model.getValueAt(i,1).toString();
        
        cartPrice=(int) model.getValueAt(i,2);
        
        cartStock=(int) model.getValueAt(i,3);
        
        cartDetail=model.getValueAt(i,4).toString();
        //JOptionPane.showMessageDialog(null,cartName);

        
        selectedItem=(int)model.getValueAt(i,0);

        // TODO add your handling code here:
    }//GEN-LAST:event_healthTableMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
panel.removeAll();
        panel.add(registeredClients);
        panel.repaint();
        panel.revalidate();         

        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
         
        JOptionPane.showMessageDialog(null,"You Paid "+cartTotal+"Rs. Thanks for Shopping with us!");
        
        int s_no=0;
    
            try {
                
                com.mysql.jdbc.PreparedStatement pst;
                String get="SELECT S_no  FROM `reciept`";
                pst =(com.mysql.jdbc.PreparedStatement) con.prepareStatement(get);
                ResultSet rs=pst.executeQuery();
                
                while(rs.next())
                {
                    s_no =rs.getInt("S_no");
                
                }
                s_no++;
                
            }
            catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            //JOptionPane.showMessageDialog(null,s_no);
        
        long millis=System.currentTimeMillis();
        Timestamp timestamp=new Timestamp(millis);
        try 
                {                                         

                    String get2="INSERT INTO `reciept` (`S_no`, `CustomerUserName`, `TotalAmount`, `datenTime`) VALUES (?, ?, ?,?)";
                    java.sql.PreparedStatement pst2;
                    pst2 = con.prepareStatement(get2);
                    pst2.setInt(1,s_no);
                    pst2.setString(2, uName);
                    pst2.setInt(3, cartTotal);
                    pst2.setTimestamp(4,timestamp );
                    

                     if(pst2.executeUpdate()>0)
                       {
                          // JOptionPane.showMessageDialog(null,"Product Added!");
                       }
                     else
                     {
                         JOptionPane.showMessageDialog(null,"error!");
                     }

               } 
                catch (SQLException ex)
                {
                    Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
         String get1="DELETE FROM `cart` WHERE `cart`.`UserName` =?";            
        try {
            java.sql.PreparedStatement pst1;
            pst1 = con.prepareStatement(get1);
            pst1.setString(1,uName);
            pst1.execute();
            
           // JOptionPane.showMessageDialog(null,"Selected Item Deleted Successfully");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutActionPerformed

    private void removeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductActionPerformed
         String get1="DELETE FROM `cart` WHERE `cart`.`S_no` ="+selectedItem;
                    
        try {
            java.sql.PreparedStatement pst1;
            pst1 = con.prepareStatement(get1);
            
            pst1.execute();
            
            JOptionPane.showMessageDialog(null,"Selected Item Deleted Successfully");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        int i=cartTable.getSelectedRow();
        model.removeRow(i);
        cartTotal=cartTotal-selectedItemTotal;
        showTotal.setText(String.valueOf(cartTotal));
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_removeProductActionPerformed
int selectedItem=0,selectedItemTotal=0;
    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        int i=cartTable.getSelectedRow();
        selectedItem=(int)model.getValueAt(i,0);
        selectedItemTotal=(int)model.getValueAt(i,4);

        // TODO add your handling code here:
    }//GEN-LAST:event_cartTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteredClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteredClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteredClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteredClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisteredClients().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegisteredClients.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane aaa;
    private javax.swing.JButton back;
    private javax.swing.JPanel beauty;
    private javax.swing.JTable beautyTable;
    private javax.swing.JPanel cart;
    private javax.swing.JButton cartButton;
    private javax.swing.JTable cartTable;
    private javax.swing.JPanel cats;
    private javax.swing.JButton checkout;
    private javax.swing.JButton clothsButton1;
    private javax.swing.JPanel electronics;
    private javax.swing.JButton electronicsButton1;
    private javax.swing.JTable electronicsTable;
    private javax.swing.JTextField getQ;
    private javax.swing.JPanel health;
    private javax.swing.JButton healthButton1;
    private javax.swing.JTable healthTable;
    private javax.swing.JScrollPane hhh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel registeredClients;
    private javax.swing.JButton removeProduct;
    private javax.swing.JLabel setUsername;
    private javax.swing.JLabel showTotal;
    private javax.swing.JPanel sports;
    private javax.swing.JButton sportsButton1;
    private javax.swing.JTable sportsTable;
    private javax.swing.JScrollPane sss;
    // End of variables declaration//GEN-END:variables

     public void retrieveElectronics() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) electronicsTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0,productId;
        PreparedStatement pst;
        String get="SELECT ProductID,Name,Price,stock,Detail  FROM `product` WHERE Category='electronics'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            productId=rs.getInt("ProductID");
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
              Object data[]={productId,name,price,stock,detail};
            eTable.addRow(data);
            
        }   
    }
     public void retrieveSports() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) sportsTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0,productId=0;
        PreparedStatement pst;
        String get="SELECT ProductID,Name,Price,stock,Detail  FROM `product` WHERE Category='sports'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            productId=rs.getInt("ProductID");
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
          
            Object data[]={productId,name,price,stock,detail};
            eTable.addRow(data);
            
        }   
    }
     public void retrieveBeauty() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) beautyTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0,productId=0;
        PreparedStatement pst;
        String get="SELECT ProductID,Name,Price,stock,Detail  FROM `product` WHERE Category='beauty'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            productId=rs.getInt("ProductID");
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
            
            Object data[]={productId,name,price,stock,detail};
            eTable.addRow(data); 
        }   
    }
     public void retrieveHealth() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) healthTable.getModel();
         eTable.setRowCount(0);
        String name,detail;
        int price=0,stock=0,productId=0;
        PreparedStatement pst;
        String get="SELECT ProductID,Name,Price,stock,Detail  FROM `product` WHERE Category='health'";
        pst =(PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            productId=rs.getInt("ProductID");
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Stock");
            detail =rs.getString("Detail");
            //JOptionPane.showMessageDialog(null,name);
            
            Object data[]={productId,name,price,stock,detail};
            eTable.addRow(data);
            
        }   
    }
     
     public void retrieveData() throws SQLException
    {
         DefaultTableModel eTable = (DefaultTableModel) cartTable.getModel();
         eTable.setRowCount(0);
        String name,detail,category;
        int id,price=0,stock=0;
        com.mysql.jdbc.PreparedStatement pst;
        String get="SELECT S_no,Name,Price,Items  FROM `cart` WHERE UserName="+uName;
        pst =(com.mysql.jdbc.PreparedStatement) con.prepareStatement(get);
        ResultSet rs=pst.executeQuery();
        
        while(rs.next())
        {
            id=rs.getInt("S_no");
            name =rs.getString("Name");
            price =rs.getInt("Price");
            stock =rs.getInt("Items");
           
            //JOptionPane.showMessageDialog(null,name);
            
                Object data[]={id,name,price,stock};
            eTable.addRow(data); 
        }   
    }
    
}
